# Generated by Django 5.0.2 on 2024-05-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('course_title', models.CharField(max_length=100)),
                ('course_credit', models.DecimalField(decimal_places=2, max_digits=3)),
                ('course_timeperweek', models.DecimalField(decimal_places=2, max_digits=3)),
                ('course_content', models.TextField()),
                ('is_lab_course', models.BooleanField(default=False)),
                ('is_diploma_course', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('room_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_lab', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('evening_slot', models.BooleanField(default=False)),
                ('class_slots', models.ManyToManyField(to='api.classslot')),
            ],
            options={
                'unique_together': {('day', 'evening_slot')},
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_semester', models.CharField(choices=[('1.1', '1st Year 1st Semester'), ('1.2', '1st Year 2nd Semester'), ('2.1', '2nd Year 1st Semester'), ('2.2', '2nd Year 2nd Semester'), ('3.1', '3rd Year 1st Semester'), ('3.2', '3rd Year 2nd Semester'), ('4.1', '4th Year 1st Semester'), ('4.2', '4th Year 2nd Semester')], max_length=3, primary_key=True, serialize=False, unique=True)),
                ('is_diploma_curriculum', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_instructors', models.ManyToManyField(to='api.courseinstructor')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='GenetareSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_days', models.ManyToManyField(to='api.classslots')),
                ('class_schedule', models.ManyToManyField(to='api.classschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('designation', models.CharField(choices=[('L', 'Lecturer'), ('SL', 'Senior Lecturer'), ('P', 'Professor'), ('AP', 'Adjunct Professor'), ('AS', 'Assistant Professor'), ('DH', 'Departmental Head'), ('AD', 'Adjunct')], max_length=2)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('CE', 'Civil Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('ENG', 'English Language and Literature'), ('LAW', 'Law'), ('BBA', 'Business Studies'), ('GST', 'Guest')], max_length=3)),
                ('is_guest', models.BooleanField(default=False)),
                ('preferred_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.classslot')),
            ],
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='instructors',
            field=models.ManyToManyField(to='api.instructor'),
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=1)),
                ('is_evening', models.BooleanField(default=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curriculum')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
            options={
                'unique_together': {('curriculum', 'room', 'section_name')},
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='rooms',
            field=models.ManyToManyField(to='api.roomschedule'),
        ),
    ]
