# Generated by Django 5.0.2 on 2024-05-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenetareSchedule',
            new_name='GenerateSchedule',
        ),
    ]
