# Generated by Django 5.0.2 on 2024-05-05 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='room',
        ),
        migrations.AddField(
            model_name='course',
            name='is_lab_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='preferred_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.classslot'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GenetareSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_days', models.ManyToManyField(to='api.classslots')),
                ('class_schedule', models.ManyToManyField(to='api.classschedule')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=1)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curriculum')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
            options={
                'unique_together': {('curriculum', 'room', 'section_name')},
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='rooms',
            field=models.ManyToManyField(to='api.roomschedule'),
        ),
    ]
