# Generated by Django 5.0.2 on 2024-03-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='courses',
            field=models.ManyToManyField(related_name='curriculums', to='api.course'),
        ),
    ]
