# Generated by Django 5.0.2 on 2024-03-11 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_course_curriculum_curriculum_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.curriculum'),
        ),
    ]
