# Generated by Django 5.0.2 on 2024-05-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_genetareschedule_generateschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generateschedule',
            old_name='class_schedule',
            new_name='class_schedules',
        ),
    ]
