# Generated by Django 5.0.2 on 2024-05-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_class_schedule_generateschedule_class_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_depertmental_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='designation',
            field=models.CharField(choices=[('L', 'Lecturer'), ('SL', 'Senior Lecturer'), ('P', 'Professor'), ('AP', 'Adjunct Professor'), ('AS', 'Assistant Professor'), ('AD', 'Adjunct')], max_length=2),
        ),
    ]
