# Generated by Django 5.0.2 on 2024-03-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_curriculum_courses_course_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='courses',
            field=models.ManyToManyField(related_name='curriculums', to='api.course'),
        ),
    ]
