# Generated by Django 5.0.2 on 2024-05-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_curriculum_options_alter_instructor_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.DeleteModel(
            name='CourseInstructor',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
        migrations.DeleteModel(
            name='GenerateSchedule',
        ),
        migrations.DeleteModel(
            name='RoomSchedule',
        ),
    ]
