# Generated by Django 5.0.2 on 2024-05-12 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_curriculum_courseinstructor_classschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
