# Generated by Django 5.0.2 on 2024-05-12 15:25

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Course = apps.get_model("api", "Course")
    for row in Course.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
