# Generated by Django 5.0.2 on 2024-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_course_course_code_alter_course_uuid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.DeleteModel(
            name='CourseInstructor',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
        migrations.DeleteModel(
            name='GenerateSchedule',
        ),
        migrations.DeleteModel(
            name='RoomSchedule',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=12),
        ),
    ]
