# Generated by Django 5.0.2 on 2024-05-12 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_course_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_semester', models.CharField(choices=[('1.1', '1st Year 1st Semester'), ('1.2', '1st Year 2nd Semester'), ('2.1', '2nd Year 1st Semester'), ('2.2', '2nd Year 2nd Semester'), ('3.1', '3rd Year 1st Semester'), ('3.2', '3rd Year 2nd Semester'), ('4.1', '4th Year 1st Semester'), ('4.2', '4th Year 2nd Semester')], max_length=3)),
                ('is_diploma_curriculum', models.BooleanField(default=False)),
                ('courses', models.ManyToManyField(to='api.course')),
            ],
            options={
                'ordering': ['curriculum_semester', 'is_diploma_curriculum'],
                'unique_together': {('curriculum_semester', 'is_diploma_curriculum')},
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('instructors', models.ManyToManyField(to='api.instructor')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_instructors', models.ManyToManyField(to='api.courseinstructor')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='GenerateSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_days', models.ManyToManyField(to='api.classslots')),
                ('class_schedules', models.ManyToManyField(to='api.classschedule')),
            ],
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=1)),
                ('is_evening', models.BooleanField(default=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curriculum')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
            options={
                'unique_together': {('curriculum', 'room', 'section_name')},
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='rooms',
            field=models.ManyToManyField(to='api.roomschedule'),
        ),
    ]
